[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"
  environment = { SECRETS_SCAN_OMIT_KEYS = "NODE_ENV", SECRETS_SCAN_OMIT_PATHS = ".env,.env.bak,render.yaml,vercel.json,node_modules/**/*,dist/**/*,netlify/functions/**/*,src/**/*,package.json" }

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200